name: Build My Application

on: [push]

jobs:
  build:
    name: Build Our App
    runs-on: ubuntu-latest
    steps:
      - name: Print current directory
        run: pwd
      - name: List files in directory
        run: ls
